### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by maur134** [hyperdownload/SGAF#1]
Error al loguearse, ayer funcionaba hoy no👻

File "c:\xampp\htdocs\proyecto\SGAF\pruebaflask.py", line 25, in login
      print(hashlib.sha256(password.encode()).hexdigest() , base.get_property_user('Password', email))

File "c:\xampp\htdocs\proyecto\SGAF\Elbase.py", line 149, in get_property_user
      return dat[0]

TypeError: 'NoneType' object is not subscriptable

**Comment by InnoDev69** [comment]
Lagarto

**Comment by InnoDev69** [comment]
Ya lo solucione
